### ISSUE TITLE
[1.10.2] - ClientConnectionEvent$Join

### ISSUE THREAD

**Issue by comdarksider** [EverCraft/EverAPI#1]
Could not pass ClientConnectionEvent$Join$Impl to Plugin

Link error :
1. Pastebin -  http://pastebin.com/TCb9yadn
2. Git hub -  https://gist.github.com/comdarksider/eccceb2268518685093c2000997b8fb6

**Comment by rexbut** [comment]
Can you send me the file : "/config/everinformations/nametag.conf"

**Comment by comdarksider** [comment]
Your plugins not support plugins of LuckPerms | An advanced permissions system for prefix and suffix.

**Comment by comdarksider** [comment]
My file nametag.conf
Link :  http://www.mediafire.com/file/rsog6xgpn5i9cmr/nametag.conf

**Comment by rexbut** [comment]
> Your plugins not support plugins of LuckPerms | An advanced permissions system for prefix and suffix.

Yes but be careful, because a prefix (or suffix) must be less than or equal to 16 characters.

**Comment by comdarksider** [comment]
I use pex in same problem.  Example my prefix for admin is [ADMIN]

**Comment by comdarksider** [comment]
How to fix this problem because some player have over 16 characters.

**Comment by comdarksider** [comment]
Please fix this error.

**Comment by rexbut** [comment]
Normally there will never be an error again but the prefix and suffix values ​​can not exceed 16 characters.

I recompiled the plugins: http://evercraft.fr/jenkins/job/EverCraft/job/EverPlugins/job/stable-5/
