### ISSUE TITLE
[1.12.2] Error at launch with spongeforge

### ISSUE THREAD

**Issue by HestiaLesb** [EverCraft/EverAPI#3]
Hi!
I get these errors when i start my server and i can't use the everplugins command.
https://pastebin.com/mpyWyQ4c
Some help please? 😄

**Comment by lesbleu** [comment]
Hi,

Recently Sponge added a new Cause implementation. EverApi and EverCraft plugins is not compatible with the latest version. Normally, the implementation of Cause in EverCraft Plugins will be done before the end of the month.

I keep you informed.

**Comment by HestiaLesb** [comment]
Thanks for this quick answer, i will be patient.
